# Generated by matugen — do not edit by hand.
set -g fish_color_normal --reset
set -g fish_color_autosuggestion {{ colors.outline.default.hex_stripped }}
set -g fish_color_cancel --reverse
set -g fish_color_command {{ colors.primary.default.hex_stripped }}
set -g fish_color_comment {{ colors.outline.default.hex_stripped }} --italics
set -g fish_color_cwd {{ colors.primary_container.default.hex_stripped }}
set -g fish_color_cwd_root {{ colors.error.default.hex_stripped }}
set -g fish_color_end {{ colors.secondary.default.hex_stripped }}
set -g fish_color_error {{ colors.error.default.hex_stripped }}
set -g fish_color_escape {{ colors.tertiary_container.default.hex_stripped }}
set -g fish_color_history_current {{ colors.on_background.default.hex_stripped }} --bold
set -g fish_color_host {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_host_remote {{ colors.error_container.default.hex_stripped }}
set -g fish_color_keyword {{ colors.primary_container.default.hex_stripped }}
set -g fish_color_operator {{ colors.primary_container.default.hex_stripped }}
set -g fish_color_option {{ colors.primary.default.hex_stripped }}
set -g fish_color_param {{ colors.tertiary_container.default.hex_stripped }}
set -g fish_color_quote {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_redirection {{ colors.secondary.default.hex_stripped }} --bold
set -g fish_color_search_match --background={{ colors.surface_container.default.hex_stripped }} --bold
set -g fish_color_selection {{ colors.on_background.default.hex_stripped }} --background={{ colors.surface_container.default.hex_stripped }} --bold
set -g fish_color_status {{ colors.error.default.hex_stripped }}
set -g fish_color_user {{ colors.tertiary.default.hex_stripped }}
set -g fish_color_valid_path --underline
